name: CI_Airflow_Update

on:
  push:
    branches: [ no ci ]
  pull_request:
    branches: [ no ci ]

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      # 2. Extract Version from VERSION file
      - name: Extract Version
        id: extract_version
        run: |
          app_version=$(cat VERSION || echo "0.0.1-dev")
          echo "EXTRACTED_VERSION=${app_version}" >> "$GITHUB_OUTPUT"

      # 3. Log in to Remote Server
      - name: SSH Login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Logged in to remote server"

      # 4. Update DAGs and Custom Scripts
      - name: Update DAGs and Custom Scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rsync -avz --delete ./dags/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/opt/airflow/dags/
            rsync -avz --delete ./plugins/custom_scripts/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/opt/airflow/plugins/custom_scripts/
            docker restart airflow-webserver
            docker restart airflow-scheduler